### ISSUE TITLE
Remapping long reads with minimap2 or NGMLR

### ISSUE THREAD

**Issue by JYLeeBioinfo** [nspies/svviz2#66]
Hello!

I wonder if you could let me know what tags the remapped BAM should be equipped with.

I want to customize some parts of the source code so that svviz2 may remap reads with the mappers other than bwa or ssw.

Since I am dealing with nanopore sequencing data, the choices are minimap2 or NGMLR.

Could you comment on what are the tags that are necessary for the remapped BAM?

Thank you,
Jin-Young

**Comment by flysheeeep** [comment]
Hey! I have the same question that visualize the SV called with bam file aligned with minimap2, have u figured it out? looking forward your reply.

**Comment by jamesdalg** [comment]
I also would find it useful. A lot of the public and private data is moving to long reads now. If the tool can be updated to take inputs from minimap2... that would be amazing. There are a few tools out there that do proper SV validation, but not many.

**Comment by nspies** [comment]
svviz2 was designed to work with long-read data, so your current read data should be working fine as-is.

I believe you're asking about how to use a next-gen aligner such as minimap2 for the realignments that svviz2 is performing - presumably you expect better alignment speed and/or accuracy using minimap2 rather than the currently supported ssw and bwa?

You should be able to add an option for an additional aligner [here](https://github.com/nspies/svviz2/blob/master/src/svviz2/app/genomesource.py#L137) that accepts as argument a read sequence and returns a list of possible alignments as `pysam.AlignedSegment()` instances. An example of how svviz2 currently wraps bwa is [here](https://github.com/nspies/pyseqlib/blob/master/src/seqlib/__init__.py#L23). It looks like minimap2 has a [python interface](https://github.com/lh3/minimap2/blob/master/python/mappy.pyx) that should be straightforward to swap in.

I believe the cigar string and `AS` tag are required but it's possible that svviz2 is using additional information from the aligner - I haven't touched this code in 5+ years, so if you're interested in pursuing this, I'd just swap in the mappy module and add features as necessary.

I'm no longer able to do any development on svviz2 but happy to accept pull requests that are easy to read and include some tests (for example, [these tests](https://github.com/nspies/svviz2/blob/master/test/test_genomesource.py) should run with your new aligner).

**Comment by JYLeeBioinfo** [comment]
Thank you for your reply! Unfortunatelt i am too not working on long-read project now... I'll try your suggestions when I have long read projects in the future. Thank you!

**Comment by flysheeeep** [comment]
Thanks a lot for your reply and suggestion @nspies , that's do me a great favour and I will have a try soon!
